[package]
name = "iamf-obu"
description = "Bitstream model and parser for IAMF (Immersive Audio Model and Formats) OBUs and descriptors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["iamf", "audio", "spatial-audio", "decoder", "eclipsa"]
categories = ["multimedia::audio", "multimedia::encoding"]

[dependencies]

[lints]
workspace = true
