[package]
name = "iamf-dec"
description = "IAMF decoding pipeline: substream decode, element reconstruction, rendering, mixing, post-processing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
iamf-obu = { path = "../iamf-obu" }

[lints]
workspace = true
