//! Render conformance against libiamf's rendered reference WAVs (fetch
//! with tools/fetch_vectors.sh; each case skips when its files are absent).
//!
//! Same-layout rendering is bit-exact. Cross-layout rendering is allowed a
//! small LSB tolerance: the references are generated by iamf-tools, whose
//! renderer arithmetic differs from libiamf's f32 tables at the last bit.

use std::path::PathBuf;

use iamf_codecs::DefaultFactory;
use iamf_dec::layout::SoundSystem;
use iamf_dec::presentation::{Descriptors, PresentationDecoder};
use iamf_obu::{AudioFrame, ObuIter};

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/vectors")
}

/// Minimal 16-bit PCM RIFF reader.
fn read_wav_s16(path: &std::path::Path) -> Option<(u16, Vec<i16>)> {
    let data = std::fs::read(path).ok()?;
    if &data[..4] != b"RIFF" || &data[8..12] != b"WAVE" {
        return None;
    }
    let mut pos = 12;
    let mut channels = 0u16;
    while pos + 8 <= data.len() {
        let id = &data[pos..pos + 4];
        let size = u32::from_le_bytes(data[pos + 4..pos + 8].try_into().unwrap()) as usize;
        let body = &data[pos + 8..(pos + 8 + size).min(data.len())];
        match id {
            b"fmt " => channels = u16::from_le_bytes(body[2..4].try_into().unwrap()),
            b"data" => {
                let samples = body
                    .chunks_exact(2)
                    .map(|b| i16::from_le_bytes([b[0], b[1]]))
                    .collect();
                return Some((channels, samples));
            }
            _ => {}
        }
        pos += 8 + size + (size & 1);
    }
    None
}

/// Matches libiamf's FLOAT2INT16.
fn quantize(x: f32) -> i16 {
    (x * 32768.0).clamp(-32768.0, 32767.0).round_ties_even() as i16
}

fn render_case(vector: &str, layout_index: usize, sound_system: u8, tolerance: i32) {
    let dir = vectors_dir();
    let iamf_path = dir.join(format!("{vector}.iamf"));
    let ref_path = dir.join(format!(
        "{vector}_rendered_id_42_sub_mix_0_layout_{layout_index}.wav"
    ));
    let (Ok(data), Some((ref_channels, reference))) =
        (std::fs::read(&iamf_path), read_wav_s16(&ref_path))
    else {
        eprintln!("{vector}: files missing; run tools/fetch_vectors.sh");
        return;
    };

    let descriptors = Descriptors::collect(&data).unwrap();
    let target = SoundSystem::from_u8(sound_system).unwrap();
    let mut decoder = PresentationDecoder::new(&descriptors, 0, target, &DefaultFactory).unwrap();
    for obu in ObuIter::new(&data).map(Result::unwrap) {
        if let Some(frame) = AudioFrame::from_obu(&obu).unwrap() {
            decoder.decode_frame(&frame).unwrap();
        }
    }
    let mix = decoder.finish().unwrap();

    assert_eq!(
        mix.channels,
        usize::from(ref_channels),
        "{vector}: channel count"
    );
    let ours: Vec<i16> = mix.interleaved.iter().map(|&s| quantize(s)).collect();
    assert_eq!(ours.len(), reference.len(), "{vector}: sample count");
    let max_diff = ours
        .iter()
        .zip(&reference)
        .map(|(&a, &b)| (i32::from(a) - i32::from(b)).abs())
        .max()
        .unwrap_or(0);
    assert!(
        max_diff <= tolerance,
        "{vector}: max diff {max_diff} exceeds tolerance {tolerance}"
    );
}

#[test]
fn stereo_passthrough_bit_exact() {
    render_case("test_000002", 0, 0, 0);
}

#[test]
fn foa_to_stereo() {
    render_case("test_000038", 0, 0, 1);
}

#[test]
fn surround_714_passthrough_bit_exact() {
    render_case("test_000070", 2, 9, 0);
}

#[test]
fn surround_714_to_stereo() {
    render_case("test_000070", 0, 0, 1);
}

#[test]
fn surround_714_to_712() {
    render_case("test_000070", 1, 10, 3);
}

#[test]
fn surround_512_to_stereo() {
    render_case("test_000069", 0, 0, 1);
}
